# Copyright (c) stefan6419846. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# See http://www.apache.org/licenses/LICENSE-2.0 for the license text.

from pathlib import Path

from license_tools.tools.scancode_tools import (
    FileResults,
    LicenseClue,
    LicenseDetection,
    LicenseMatch,
    Licenses,
)
from tests import Download

SETUP_PATH = Path(__file__).parent / "files" / "setup.py"
LICENSE_PATH = Path(__file__).parent.parent / "LICENSE.txt"


TYPING_EXTENSIONS__4_8_0__WHEEL = Download(
    url="https://files.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl",
    name="typing_extensions-4.8.0-py3-none-any.whl",
    suffix=".whl",
)

TYPING_EXTENSIONS__4_8_0__SDIST = Download(
    url="https://files.pythonhosted.org/packages/1f/7a/8b94bb016069caa12fc9f587b28080ac33b4fbb8ca369b98bc0a4828543e/typing_extensions-4.8.0.tar.gz",
    name="typing_extensions-4.8.0.tar.gz",
    suffix=".tar.gz",
)

LIBAIO1__0_3_109_1_25__RPM = Download(
    url="https://download.opensuse.org/distribution/leap/15.6/repo/oss/x86_64/libaio1-0.3.109-1.25.x86_64.rpm",
    name="libaio1-0.3.109-1.25.x86_64.rpm",
    suffix=".rpm",
)

LIBAIO1__0_3_109_1_25__SRC_RPM = Download(
    url="https://download.opensuse.org/source/distribution/leap/15.6/repo/oss/src/libaio-0.3.109-1.25.src.rpm",
    name="libaio1-0.3.109-1.25.src.rpm",
    suffix=".src.rpm",
)

PYPDF__3_17_4__WHEEL = Download(
    url="https://files.pythonhosted.org/packages/29/10/055b649e914ad8c5d07113c22805014988825abbeff007b0e89255b481fa/pypdf-3.17.4-py3-none-any.whl",
    name="pypdf-3.17.4-py3-none-any.whl",
    suffix=".whl",
)

JWCRYPTO__1_5_4__TAR_GZ = Download(
    url="https://files.pythonhosted.org/packages/13/f8/7b0a3e7ad80c04b8a020fa3061e4df8987a7d3c92f9ddc6552e4e908706b/jwcrypto-1.5.4.tar.gz",
    name="jwcrypto-1.5.4.tar.gz",
    suffix=".tar.gz",
)

JSON__20231013__JAR = Download(
    url="https://repo1.maven.org/maven2/org/json/json/20231013/json-20231013.jar",
    name="json-20231013.jar",
    suffix=".jar",
)

BASE64__0_22_0__CRATE = Download(
    url="https://crates.io/api/v1/crates/base64/0.22.0/download",
    name="base64_0.22.0.crate",
    suffix=".crate",
)

# In theory, the URL should be identical to https://raw.githubusercontent.com/marshallpierce/rust-base64/refs/tags/v0.22.0/Cargo.toml,
# but it appears to be broken and/or returns data for version 0.22.1.
BASE64__0_22_0__CARGO_TOML = Download(
    url="https://github.com/marshallpierce/rust-base64/raw/5d70ba7576f9aafcbf02bd8acfcb9973411fb95f/Cargo.toml",
    name="Cargo.toml",
    suffix=".toml",
)

CRYPTOGRAPHY__42_0_0__CARGO_LOCK = Download(
    url="https://github.com/pyca/cryptography/raw/42.0.0/src/rust/Cargo.lock",
    name="Cargo.lock",
    suffix=".lock",
)

DJANGO__5076BB4__DJANGO_MO = Download(
    url="https://github.com/django/django/raw/8d9901c961bf9d5cfa6bddddbbcebfbf487a5125/django/contrib/admin/locale/de/LC_MESSAGES/django.mo",
    name="django.mo",
    suffix=".mo",
)

DJANGO__5076BB4__DJANGO_PO = Download(
    url="https://github.com/django/django/raw/8d9901c961bf9d5cfa6bddddbbcebfbf487a5125/django/contrib/admin/locale/de/LC_MESSAGES/django.po",
    name="django.po",
    suffix=".po",
)


# Generated by `scancode-toolkit==32.0.8`.
SETUP_PY_LICENSES = Licenses(
    detected_license_expression="apache-2.0",
    detected_license_expression_spdx="Apache-2.0",
    percentage_of_license_text=19.34,
    license_detections=[
        LicenseDetection(
            license_expression="apache-2.0",
            license_expression_spdx="Apache-2.0",
            identifier="apache_2_0-1e5a86d5-35db-eb02-fd60-5cbcf1ec1d21",
            matches=[
                LicenseMatch(
                    score=100.0,
                    start_line=2,
                    end_line=2,
                    matched_length=6,
                    match_coverage=100.0,
                    matcher="1-spdx-id",
                    license_expression="apache-2.0",
                    license_expression_spdx="Apache-2.0",
                    rule_identifier="spdx-license-identifier-apache_2_0-5dcda840588b4f07f49f2c0100924ebca7bc0649",
                    rule_relevance=100,
                    rule_url=None,
                    from_file=None,
                    matched_text=None,
                ),
                LicenseMatch(
                    score=100.0,
                    start_line=3,
                    end_line=3,
                    matched_length=13,
                    match_coverage=100.0,
                    matcher="2-aho",
                    license_expression="apache-2.0",
                    license_expression_spdx="Apache-2.0",
                    rule_identifier="apache-2.0_1251.RULE",
                    rule_relevance=100,
                    rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/apache-2.0_1251.RULE",
                    from_file=None,
                    matched_text=None,
                ),
            ],
        ),
        LicenseDetection(
            license_expression="apache-2.0",
            license_expression_spdx="Apache-2.0",
            identifier="apache_2_0-ec759ae0-ea5a-f138-793e-388520e080c0",
            matches=[
                LicenseMatch(
                    score=100.0,
                    start_line=17,
                    end_line=17,
                    matched_length=4,
                    match_coverage=100.0,
                    matcher="2-aho",
                    license_expression="apache-2.0",
                    license_expression_spdx="Apache-2.0",
                    rule_identifier="apache-2.0_65.RULE",
                    rule_relevance=100,
                    rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/apache-2.0_65.RULE",
                    from_file=None,
                    matched_text=None,
                ),
            ],
        ),
        LicenseDetection(
            license_expression="apache-2.0",
            license_expression_spdx="Apache-2.0",
            identifier="apache_2_0-e267f9d9-ae62-e9c9-9cc2-8cd0a1e4928f",
            matches=[
                LicenseMatch(
                    score=95.0,
                    start_line=53,
                    end_line=53,
                    matched_length=6,
                    match_coverage=100.0,
                    matcher="2-aho",
                    license_expression="apache-2.0",
                    license_expression_spdx="Apache-2.0",
                    rule_identifier="pypi_apache_no-version.RULE",
                    rule_relevance=95,
                    rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/pypi_apache_no-version.RULE",
                    from_file=None,
                    matched_text=None,
                ),
            ],
        ),
    ],
    license_clues=[
        LicenseClue(
            score=50.0,
            start_line=15,
            end_line=15,
            matched_length=3,
            match_coverage=100.0,
            matcher="2-aho",
            license_expression="free-unknown",
            license_expression_spdx="LicenseRef-scancode-free-unknown",
            rule_identifier="free-unknown_88.RULE",
            rule_relevance=50,
            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/free-unknown_88.RULE",
            from_file=None,
            matched_text=None,
        ),
        LicenseClue(
            score=50.0,
            start_line=59,
            end_line=59,
            matched_length=3,
            match_coverage=100.0,
            matcher="2-aho",
            license_expression="free-unknown",
            license_expression_spdx="LicenseRef-scancode-free-unknown",
            rule_identifier="free-unknown_88.RULE",
            rule_relevance=50,
            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/free-unknown_88.RULE",
            from_file=None,
            matched_text=None,
        ),
    ],
)

TYPING_EXTENSION_4_8_0__WHEEL_FILES = [
    "typing_extensions-4.8.0.dist-info/LICENSE",
    "typing_extensions-4.8.0.dist-info/METADATA",
    "typing_extensions-4.8.0.dist-info/RECORD",
    "typing_extensions-4.8.0.dist-info/WHEEL",
    "typing_extensions.py",
]

TYPING_EXTENSION_4_8_0__SOURCE_FILES = [
    "typing_extensions-4.8.0/CHANGELOG.md",
    "typing_extensions-4.8.0/LICENSE",
    "typing_extensions-4.8.0/PKG-INFO",
    "typing_extensions-4.8.0/README.md",
    "typing_extensions-4.8.0/pyproject.toml",
    "typing_extensions-4.8.0/src/_typed_dict_test_helper.py",
    "typing_extensions-4.8.0/src/test_typing_extensions.py",
    "typing_extensions-4.8.0/src/typing_extensions.py",
    "typing_extensions-4.8.0/tox.ini",
]

# Generated by `scancode-toolkit==32.0.8`.
# `retrieve_licenses` has been set to `False` to avoid actually retrieving them.
TYPING_EXTENSION_4_8_0__LICENSES = [
    FileResults(
        path=Path("/tmp/tmpr6n2cx2i/typing_extensions-4.8.0.dist-info/LICENSE"),
        short_path="typing_extensions-4.8.0.dist-info/LICENSE",
        retrieve_copyrights=False,
        retrieve_emails=False,
        retrieve_urls=False,
        retrieve_licenses=False,
        retrieve_file_info=False,
        copyrights=None,
        emails=None,
        urls=None,
        licenses=Licenses(
            detected_license_expression="python AND gpl-1.0-plus AND (python AND bsd-new) AND (python AND bsd-new AND bsd-zero)",
            detected_license_expression_spdx="Python-2.0 AND GPL-1.0-or-later AND (Python-2.0 AND BSD-3-Clause) AND (Python-2.0 AND BSD-3-Clause AND 0BSD)",
            percentage_of_license_text=78.71,
            license_detections=[
                LicenseDetection(
                    license_expression="python",
                    license_expression_spdx="Python-2.0",
                    identifier="python-2fabfeda-748f-63e7-53be-8bc757f3180a",
                    matches=[
                        LicenseMatch(
                            score=100.0,
                            start_line=23,
                            end_line=24,
                            matched_length=7,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="python",
                            license_expression_spdx="Python-2.0",
                            rule_identifier="python_63.RULE",
                            rule_relevance=100,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/python_63.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                    ],
                ),
                LicenseDetection(
                    license_expression="gpl-1.0-plus",
                    license_expression_spdx="GPL-1.0-or-later",
                    identifier="gpl_1_0_plus-540d1532-9198-4c82-4d7b-c84ac418b631",
                    matches=[
                        LicenseMatch(
                            score=100.0,
                            start_line=44,
                            end_line=45,
                            matched_length=3,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="gpl-1.0-plus",
                            license_expression_spdx="GPL-1.0-or-later",
                            rule_identifier="gpl-1.0-plus_200.RULE",
                            rule_relevance=100,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-1.0-plus_200.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                        LicenseMatch(
                            score=85.0,
                            start_line=45,
                            end_line=45,
                            matched_length=2,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="gpl-1.0-plus",
                            license_expression_spdx="GPL-1.0-or-later",
                            rule_identifier="gpl-1.0-plus_351.RULE",
                            rule_relevance=85,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-1.0-plus_351.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                        LicenseMatch(
                            score=85.0,
                            start_line=46,
                            end_line=47,
                            matched_length=2,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="gpl-1.0-plus",
                            license_expression_spdx="GPL-1.0-or-later",
                            rule_identifier="gpl-1.0-plus_351.RULE",
                            rule_relevance=85,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-1.0-plus_351.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                    ],
                ),
                LicenseDetection(
                    license_expression="gpl-1.0-plus",
                    license_expression_spdx="GPL-1.0-or-later",
                    identifier="gpl_1_0_plus-1b302adf-b195-03df-8d4e-459bdca225aa",
                    matches=[
                        LicenseMatch(
                            score=100.0,
                            start_line=48,
                            end_line=48,
                            matched_length=4,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="gpl-1.0-plus",
                            license_expression_spdx="GPL-1.0-or-later",
                            rule_identifier="gpl_194.RULE",
                            rule_relevance=100,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl_194.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                    ],
                ),
                LicenseDetection(
                    license_expression="gpl-1.0-plus",
                    license_expression_spdx="GPL-1.0-or-later",
                    identifier="gpl_1_0_plus-0275ca3c-0d0c-8224-0676-9b6f2b7ff11c",
                    matches=[
                        LicenseMatch(
                            score=85.0,
                            start_line=53,
                            end_line=53,
                            matched_length=2,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="gpl-1.0-plus",
                            license_expression_spdx="GPL-1.0-or-later",
                            rule_identifier="gpl-1.0-plus_351.RULE",
                            rule_relevance=85,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-1.0-plus_351.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                    ],
                ),
                LicenseDetection(
                    license_expression="python",
                    license_expression_spdx="Python-2.0",
                    identifier="python-1550820c-06f5-8caa-ad51-4ed40cbe6c38",
                    matches=[
                        LicenseMatch(
                            score=100.0,
                            start_line=62,
                            end_line=63,
                            matched_length=10,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="python",
                            license_expression_spdx="Python-2.0",
                            rule_identifier="python_16.RULE",
                            rule_relevance=100,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/python_16.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                    ],
                ),
                LicenseDetection(
                    license_expression="python AND bsd-new",
                    license_expression_spdx="Python-2.0 AND BSD-3-Clause",
                    identifier="python_and_bsd_new-e30d72bf-ce53-4cf8-03bb-1ab1d7ab23f9",
                    matches=[
                        LicenseMatch(
                            score=80.0,
                            start_line=66,
                            end_line=66,
                            matched_length=4,
                            match_coverage=100.0,
                            matcher="3-seq",
                            license_expression="unknown-license-reference",
                            license_expression_spdx="LicenseRef-scancode-unknown-license-reference",
                            rule_identifier="unknown-license-reference_268.RULE",
                            rule_relevance=100,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/unknown-license-reference_268.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                        LicenseMatch(
                            score=100.0,
                            start_line=66,
                            end_line=66,
                            matched_length=2,
                            match_coverage=100.0,
                            matcher="3-seq",
                            license_expression="python",
                            license_expression_spdx="Python-2.0",
                            rule_identifier="python_34.RULE",
                            rule_relevance=100,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/python_34.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                        LicenseMatch(
                            score=99.0,
                            start_line=67,
                            end_line=67,
                            matched_length=2,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="bsd-new",
                            license_expression_spdx="BSD-3-Clause",
                            rule_identifier="bsd-new_26.RULE",
                            rule_relevance=99,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/bsd-new_26.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                    ],
                ),
                LicenseDetection(
                    license_expression="python AND bsd-new AND bsd-zero",
                    license_expression_spdx="Python-2.0 AND BSD-3-Clause AND 0BSD",
                    identifier="python_and_bsd_new_and_bsd_zero-c0222c9a-2a19-8ee7-903b-cebffd111794",
                    matches=[
                        LicenseMatch(
                            score=78.37,
                            start_line=73,
                            end_line=265,
                            matched_length=1540,
                            match_coverage=78.37,
                            matcher="3-seq",
                            license_expression="python",
                            license_expression_spdx="Python-2.0",
                            rule_identifier="python_70.RULE",
                            rule_relevance=100,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/python_70.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                        LicenseMatch(
                            score=99.0,
                            start_line=267,
                            end_line=267,
                            matched_length=2,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="bsd-new",
                            license_expression_spdx="BSD-3-Clause",
                            rule_identifier="bsd-new_26.RULE",
                            rule_relevance=99,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/bsd-new_26.RULE",
                            from_file=None,
                            matched_text=None,
                        ),
                        LicenseMatch(
                            score=100.0,
                            start_line=270,
                            end_line=279,
                            matched_length=98,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="bsd-zero",
                            license_expression_spdx="0BSD",
                            rule_identifier="bsd-zero.LICENSE",
                            rule_relevance=100,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/bsd-zero.LICENSE",
                            from_file=None,
                            matched_text=None,
                        ),
                    ],
                ),
            ],
            license_clues=[
                LicenseClue(
                    score=80.0,
                    start_line=44,
                    end_line=44,
                    matched_length=2,
                    match_coverage=100.0,
                    matcher="2-aho",
                    license_expression="other-copyleft",
                    license_expression_spdx="LicenseRef-scancode-other-copyleft",
                    rule_identifier="other-copyleft_24.RULE",
                    rule_relevance=80,
                    rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/other-copyleft_24.RULE",
                    from_file=None,
                    matched_text=None,
                ),
                LicenseClue(
                    score=80.0,
                    start_line=47,
                    end_line=47,
                    matched_length=2,
                    match_coverage=100.0,
                    matcher="2-aho",
                    license_expression="other-copyleft",
                    license_expression_spdx="LicenseRef-scancode-other-copyleft",
                    rule_identifier="other-copyleft_24.RULE",
                    rule_relevance=80,
                    rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/other-copyleft_24.RULE",
                    from_file=None,
                    matched_text=None,
                ),
                LicenseClue(
                    score=80.0,
                    start_line=50,
                    end_line=50,
                    matched_length=2,
                    match_coverage=100.0,
                    matcher="2-aho",
                    license_expression="other-copyleft",
                    license_expression_spdx="LicenseRef-scancode-other-copyleft",
                    rule_identifier="other-copyleft_24.RULE",
                    rule_relevance=80,
                    rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/other-copyleft_24.RULE",
                    from_file=None,
                    matched_text=None,
                ),
            ],
        ),
        file_info=None,
    ),
    FileResults(
        path=Path("/tmp/tmpr6n2cx2i/typing_extensions-4.8.0.dist-info/METADATA"),
        short_path="typing_extensions-4.8.0.dist-info/METADATA",
        retrieve_copyrights=False,
        retrieve_emails=False,
        retrieve_urls=False,
        retrieve_licenses=False,
        retrieve_file_info=False,
        copyrights=None,
        emails=None,
        urls=None,
        licenses=Licenses(
            detected_license_expression="python",
            detected_license_expression_spdx="Python-2.0",
            percentage_of_license_text=2.01,
            license_detections=[
                LicenseDetection(
                    license_expression="python",
                    license_expression_spdx="Python-2.0",
                    identifier="python-03cf89ce-88f1-7600-71f7-302015c97123",
                    matches=[
                        LicenseMatch(
                            score=99.0,
                            start_line=12,
                            end_line=12,
                            matched_length=8,
                            match_coverage=100.0,
                            matcher="2-aho",
                            license_expression="python",
                            license_expression_spdx="Python-2.0",
                            rule_identifier="pypi_python_software_foundation_license2.RULE",
                            rule_relevance=99,
                            rule_url="https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/pypi_python_software_foundation_license2.RULE",  # noqa: E501
                            from_file=None,
                        ),
                    ],
                ),
            ],
            license_clues=[],
        ),
        file_info=None,
    ),
    FileResults(
        path=Path("/tmp/tmpr6n2cx2i/typing_extensions-4.8.0.dist-info/RECORD"),
        short_path="typing_extensions-4.8.0.dist-info/RECORD",
        retrieve_copyrights=False,
        retrieve_emails=False,
        retrieve_urls=False,
        retrieve_licenses=False,
        retrieve_file_info=False,
        copyrights=None,
        emails=None,
        urls=None,
        licenses=Licenses(
            detected_license_expression=None,
            detected_license_expression_spdx=None,
            percentage_of_license_text=0,
            license_detections=[],
            license_clues=[],
        ),
        file_info=None,
    ),
    FileResults(
        path=Path("/tmp/tmpr6n2cx2i/typing_extensions-4.8.0.dist-info/WHEEL"),
        short_path="typing_extensions-4.8.0.dist-info/WHEEL",
        retrieve_copyrights=False,
        retrieve_emails=False,
        retrieve_urls=False,
        retrieve_licenses=False,
        retrieve_file_info=False,
        copyrights=None,
        emails=None,
        urls=None,
        licenses=Licenses(
            detected_license_expression=None,
            detected_license_expression_spdx=None,
            percentage_of_license_text=0,
            license_detections=[],
            license_clues=[],
        ),
        file_info=None,
    ),
    FileResults(
        path=Path("/tmp/tmpr6n2cx2i/typing_extensions.py"),
        short_path="typing_extensions.py",
        retrieve_copyrights=False,
        retrieve_emails=False,
        retrieve_urls=False,
        retrieve_licenses=False,
        retrieve_file_info=False,
        copyrights=None,
        emails=None,
        urls=None,
        licenses=Licenses(
            detected_license_expression=None,
            detected_license_expression_spdx=None,
            percentage_of_license_text=0,
            license_detections=[],
            license_clues=[],
        ),
        file_info=None,
    ),
]

# Remove the leading linebreak which is just used to improve display here.
TYPING_EXTENSION_4_8_0__EXPECTED_OUTPUT = """
 typing_extensions-4.8.0.dist-info/LICENSE Python-2.0 AND GPL-1.0-or-later AND (Python-2.0 AND BSD-3-Clause) AND (Python-2.0 AND BSD-3-Clause AND 0BSD) 
typing_extensions-4.8.0.dist-info/METADATA                                                             Python-2.0 [99.0]
  typing_extensions-4.8.0.dist-info/RECORD                                                                        
   typing_extensions-4.8.0.dist-info/WHEEL                                                                        
                      typing_extensions.py                                                                        

====================================================================================================

                                                                  None  3
                                                            Python-2.0  1
Python-2.0 AND GPL-1.0-or-later AND (Python-2.0 AND BSD-3-Clause) AND (Python-2.0 AND BSD-3-Clause AND 0BSD)  1
"""[1:]  # noqa: W291
